name: Release new version of service and

on:
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Lint code and check format
    uses: ./.github/workflows/_check.yaml

  test:
    name: Run tests
    needs: check
    uses: ./.github/workflows/_test.yaml

  build-and-publish:
    name: Build and publish image to Docker Hub
    needs: test
    uses: ./.github/workflows/_build_and_publish.yaml
    secrets: inherit